### ISSUE TITLE
Add Errorbars class

### ISSUE THREAD

**Issue by yalap13** [GraphingLib/GraphingLib#24]

**Comment by Oddball777** [comment]
Potential solution for default error bar style values. In plain.yml, write :
colour: "same as curve"
line_width: "same as curve"
...

Then, when plotting, as usual, check if value for parameter "colour" is given. If not, use default value specified in plain.yml. But if specified value if plain.yml is "same as curve", check what the values are for the curve and set those for the error bars instead.
