### ISSUE TITLE
[Feature request] Shapes: new shapes.py with classes

### ISSUE THREAD

**Issue by Oddball777** [GraphingLib/GraphingLib#261]
### Describe the feature
Implement plotting of basic shapes:
- Circle
- Rectangle
- Square
- Triangle
- ...

Constructor:
- Basic parameters for geometry and location
- fill_color (can be None), edge_color, alpha, line_width, line_style (all of these in style files, colors follow color cycle)

Other useful methods:
- Area
- Perimeter/circumference
- Vertices
- get curve from edge? How to specify which edge?

### Is there currently a (suboptimal?) way to do this?
Not unless you create a ton of different curves, and even then it's not simple

**Comment by yalap13** [comment]
Arrows (single sided and double sided, curved if possible, etc.) would also be useful.
