### ISSUE TITLE
[Feature request] Manual control of legend placement

### ISSUE THREAD

**Issue by Oddball777** [GraphingLib/GraphingLib#407]
### Describe the feature
Best doesn't always work. For example, it seems to ignore Hlines. Not a problem when showing the figure because the legend is draggable (though a bit annoying to move it every time) but when saving there's no way around it.

### Is there currently a (suboptimal?) way to do this?
Probably by accessing the axes?
Another way is to show, drag to desired location, then save the figure from the MPL interface.

### Describe the solution you'd like
Not sure where it should go exactly. In show/save? In Figure init?

**Comment by yalap13** [comment]
Could also add a control for the number of column in the legend.
